# Generated by Django 3.1.4 on 2022-03-28 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
