# Generated by Django 3.1.4 on 2022-06-25 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20220328_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='created_time',
        ),
        migrations.AddField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 20, 39, 51, 705535)),
        ),
    ]
