# Generated by Django 3.1.4 on 2022-06-25 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20220625_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='new_tag',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 25, 21, 23, 7, 946997)),
        ),
    ]
